### PR TITLE
Added checks for null and file:// origin

### PR DESCRIPTION
**Pull request by alvinleonard**
Added checks for null and file:// origin based on the CORS filter in Tomcat project.
https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/filters/CorsFilter.java#L818

### CODE REVIEW

**Comment by mohitsoni** [comment]
LGTM! Apparently, I have lost committer access to this repo as I moved to my new job. I have contacted one of the repo admin to grant me access again. Stay tuned.

**Comment by alvinleonard** [comment]
@mohitsoni any update on this?

**Comment by srivathsanvc** [comment]
@mohitsoni and @mohitsoni-ebay have committer access.. Pls let me know if you are not able to push?

**Comment by alvinleonard** [comment]
@mohitsoni @srivathsanvc 

Hi guys, this PR has been opened for a long time now. Is there any way we can push this into master? I am actively using this filter and would like to keep doing that.

**Comment by alvinleonard** [comment]
Any update? @mohitsoni @srivathsanvc 

2 months and counting...

**Comment by usengar** [comment]
Just noticed this thread, @mohitsoni I have write access for this org. If the PR looks good, want me to merge it?

**Comment by usengar** [comment]
One 2nd thought, its a trivial PR, merging it.

**Pull request merged**
